### ISSUE TITLE
Nuclear Blaze makes the app crash

### ISSUE THREAD

**Issue by ciucciodifuoco** [J-D-K/JKSV#217] opened 2023-10-29 14:04 UTC
Hey,

Switch Lite 17.0.0 + atmosphere 1.6.2 + hekate 6.0.7

i'm playing this game lately: https://www.nintendo.com/us/store/products/nuclear-blaze-switch/
when i do a backup (in full app mode, launching a game with R button pressed) for this game in  JKSV crashes with the error "The software closed unexpectedly" . If i do the same in Applet mode, the whole atmosphere crashes and console must be rebooted. 

The bug is easily triggerable, just do a bakcup for Nuclear Blaze

**Comment by fennectech** [comment] 2023-10-29 14:46
Possible that it has files with foreign characters in the save archive?

**Comment by J-D-K** [comment] 2023-10-30 23:30
As stated above, check the file names to see if they're all ASCII characters. See if using or ending the save name with `.zip` helps at all.

**Comment by ciucciodifuoco** [comment] 2023-11-14 22:41
Hi guys,
sorry for the late reply. I can open the game in File mode , find attached some screenshots. Where should i actually verify the presence fo non-ascii charachters?

![IMG_2680](https://github.com/J-D-K/JKSV/assets/60586420/e6af85ec-50d5-4187-8eb7-b7afa03185c2)
![IMG_2679](https://github.com/J-D-K/JKSV/assets/60586420/b8d663d3-69b1-47ba-b3cd-4f2b29ebba8b)

**Comment by J-D-K** [comment] 2023-11-15 20:47
There are none as far as I can see. The one thing that is interesting is the path on the bottom left. `sv:/  /`. It's something I'd need to investigate.

**Comment by J-D-K** [comment] 2024-07-17 18:52
I've just had it confirmed to me that these kind of games only work with ZIP files. Some games use UTF8 filenames and for some reason, even though the paths work in save containers, they don't work with the SD card... Nice one Nintendo.

**Comment by impeeza** [comment] 2024-07-18 01:07
I just «buy» the game for this issue and found:
The savegame of that tile IS INSIDE A FOLDER (DIRECTORY) WITH NO NAME, When you select the user and then the title, using the (X) menu «Title Optons» and selecting Open in File Mode:

![image](https://github.com/user-attachments/assets/46567702-ff2a-4951-b081-e5c8d92233d7)

you find the folders «.», «..» and «D»
![image](https://github.com/user-attachments/assets/11379493-40f1-4244-a5d7-e60c251c3608)

Then the savegame files are INSIDE the «no name» folder:
![image](https://github.com/user-attachments/assets/a4adef56-3af4-4a31-99d3-5797de5e85a1)

You can copy the files from that folder to any other folder on your SD, but JKSV  have trouble creating a new backup because first have to create a «no name» folder on SD:/JKSV/Nuclear Blaze/USER - YYYY.MM.DD @ HH.MM.SS" folder.  I doubt the Fat32 allow you to create that no-name folder and that's why the software crashes.

![image](https://github.com/user-attachments/assets/428e35e4-5bb7-4f3e-8d13-5ae5050b1033)
![image](https://github.com/user-attachments/assets/c84e4cfb-ddcc-4da0-8222-40ea25342dd6)

**Comment by impeeza** [comment] 2024-07-18 01:20
And yes setting saves to zip file works because zip file allows you to create a " " folder

![image](https://github.com/user-attachments/assets/133c48cd-f2dd-431b-bfde-0990196f51ca)

**Comment by J-D-K** [comment] 2024-07-18 09:44
I noticed that earlier too @impeeza. Really odd choice to be honest. The only purpose I can see for it is preventing homebrew save backups. Unfortunately JKSV has to support both for backwards compatibility with older versions and other tools that followed the JKSM 3DS backup style/structure. I can think of ways to check for it, but for only one game, that seems like a lot of effort…

**Comment by impeeza** [comment] 2024-07-19 03:06
I don't know if worth for something the bin of the Rewrite branch not only crash trying to make this backup but all atmosphere crash.

**Comment by impeeza** [comment] 2024-07-26 02:57
> I noticed that earlier too @impeeza. Really odd choice to be honest. The only purpose I can see for it is preventing homebrew save backups. Unfortunately JKSV has to support both for backwards compatibility with older versions and other tools that followed the JKSM 3DS backup style/structure. I can think of ways to check for it, but for only one game, that seems like a lot of effort…

Was I thinking what this is a unintended error on the game code is a space on a line of the original code.  this is bizarre.

**Comment by J-D-K** [comment] 2024-10-31 22:23
So, JKSV is going to start using ZIP as default instead of folders to prevent errors like these very soon. I'm going to close this because I don't see a way to make cases like this work with the folder style backups.

**Closed by J-D-K** 2024-10-31 22:23 UTC
